apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*.yaml
build:
  local:
    push: false
  artifacts:
    - image: ab1994/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: ab1994/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '/*.js'
            dest: .
    - image: ab1994/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '/*.js'
            dest: .
    - image: ab1994/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '/*.js'
            dest: .
    - image: ab1994/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '/*.js'
            dest: .
    - image: ab1994/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '/*.js'
          
